@echo off
echo Installing root dependencies...
call npm install
echo Installing frontend dependencies...
call npm --prefix frontend install
echo Building frontend...
call npm run build
echo Starting server...
call npm start
